### PR TITLE
Update Build Status Badge in README

### PR DESCRIPTION
**Pull request by ynamiki**
Update the build status badge in README because of #17.

### CODE REVIEW

**Review by nhoriguchi — APPROVED** [review]
looks good to me.

**Comment by sergefdrv** [comment]
I just seen #23. I think it is better to change the badge in that PR. These PRs would have a merge conflict anyway, since #23 touches the next line, which is a context line for this PR...

**Review by sergefdrv — COMMENTED** [review]
https://github.com/hyperledger-labs/minbft/pull/22#issuecomment-411679902

**Comment by ynamiki** [comment]
Merged to PR #25.

**Pull request closed without merging**
