### PR TITLE
NewView message handling

### LINKED ISSUE #179: Implement NewView message handling

### PR DESCRIPTION
**Pull request by sergefdrv**
This pull request finishes implementing handling of view-change message types.

Resolves: #179.

### CODE REVIEW

**Comment by sergefdrv** [comment]
NB. This PR is based on #238.

**Review by nhoriguchi — DISMISSED** [review]
I read through a whole patchset and didn't find any issue, so it's fine to me. I also confirmed with the sample application that minbft cluster can still process the request even if the original primary replica 0 is down thanks to view-change. This is a huge step :+1:

**Comment by sergefdrv** [comment]
@nhoriguchi Thank you for reviewing this PR. After I've made myself a fresh look at it, I'm not sure about the commit 17fc41cf0a9b33b3ca69fcd9d9797a4eee0df258. I'm afraid this change will allow Byzantine backup replicas skip initial commitments in a view. I consider dropping that commit and adjusting the code accordingly.

**Comment by sergefdrv** [comment]
Summary of [changes](https://github.com/hyperledger-labs/minbft/compare/98d8a53a1669d1abc50a74624cd41e474cf8d0fc..7f78c9648fe9c9c526660874657952b8a186949a): dropped commit 17fc41c.

**Review by nhoriguchi — APPROVED** [review]

**Pull request merged**
