### PR TITLE
Revert "CircleCI: Upgrade to SGX SDK 2.3.1"

### PR DESCRIPTION
**Pull request by nhoriguchi**
Reverts hyperledger-labs/minbft#32

Because change is requested.
Please see #34.

### CODE REVIEW

**Comment by nhoriguchi** [comment]
I wrongly created revert request, mistaking #34 as an overwrite of #32. They are just separate updates, so no need to this revert. My apology for this noise.

**Comment by sergefdrv** [comment]
@Naoya-Horiguchi Could you please delete `revert-32-sgx-2.3.1` branch?

**Comment by nhoriguchi** [comment]
@sergefdrv I've deleted. This branch was a protected branch, so in order to delete it I temporarily changed branch protection rule to cover only `master` branch.  I never intended to push a development branch to hyperledger-labs/minbft, so maybe that was just my mishandling, sorry about that.

**Comment by sergefdrv** [comment]
> I never intended to push a development branch to hyperledger-labs/minbft, so maybe that was just my mishandling, sorry about that.

@Naoya-Horiguchi No problem, I think that was early on, before we decided to use private forks for pull requests :slightly_smiling_face:

**Pull request closed without merging**
