### PR TITLE
core/internal/requestlist: Fix test case parsing

### PR DESCRIPTION
**Pull request by sergefdrv**
This pull request fixes unit test of `core/internal/requestlist` package.

### CODE REVIEW

**Review by nhoriguchi — COMMENTED** [review]
I'm not sure why you have to extend visibility of fields in internal structure here. Is that to fix any specific issue on testing? I guess that this is a preparatory work for coming changes, if so, that's OK.

**Review by ynamiki — COMMENTED** [review]
Exactly the same comment from Naoya.

**Comment by sergefdrv** [comment]
> I'm not sure why you have to extend visibility of fields in internal structure here. Is that to fix any specific issue on testing?

Sorry, I should have clarified that in the commit message. I noticed this when trying to rework unit test of `viewstate` package in similar manner. The issue is that `yaml.Unmarshal` cannot set unexported fields. Moreover, it silently ignores any field it cannot match against the input, so the fields are left unchanged. That is why I also changed to use `yaml.UnmarshalStrict` which returns error in such case.

Now this commit has to be rebased, I will mention the rationale in the commit message.

**Comment by sergefdrv** [comment]
Summary of [changes](https://github.com/hyperledger-labs/minbft/compare/efcf70ca873c574981cbab09bbc2f7e9eacaf335..c47bfc953e082f8709a445d4d595855cc3e1ab4c): rebase with conflict resolution

**Review by nhoriguchi — APPROVED** [review]
Very informative. Thank you for the fix.

**Review by ynamiki — APPROVED** [review]
Thanks for the fix!

References:
- [Minimum test code](https://play.golang.org/p/hlPraHlgf1H)
- [`Unmarshal()` document](https://godoc.org/gopkg.in/yaml.v2#Unmarshal)

**Pull request merged**
