### PR TITLE
readme: Describe the concept of USIG

### LINKED ISSUE #9: Definition of USIG
USIG seems to be a core component of MinBFT, but the terminology is not defined anywhere. Google search shows that USIG means Unique Sequential Identifier Generator, so showing this words somewhere in README will be helpful.

### PR DESCRIPTION
**Pull request by sergefdrv**
USIG is a core component of MinBFT, so it worth to describe it better
in the Concepts section of Readme.

Signed-off-by: Sergey Fedorov <sergey.fedorov@neclab.eu>

Resolves #9

### CODE REVIEW

**Review by nhoriguchi — APPROVED** [review]
The description becomes better, thank you.

**Comment by sergefdrv** [comment]
@ynamiki How do we merge reviewed pull requests?

**Comment by ynamiki** [comment]
@Naoya-Horiguchi Based on our discussion in #12, could you merge this request?

**Comment by sergefdrv** [comment]
@Naoya-Horiguchi do you have permission to merge this?

**Comment by ynamiki** [comment]
@Naoya-Horiguchi Thanks, could you delete the merged branch `9-definition-of-usig`? You'll see "Delete branch" button on this page.

**Pull request merged**
