### PR TITLE
Handle generated messages asynchronously

### PR DESCRIPTION
**Pull request by sergefdrv**
This pull request prepares message handling code for introducing new message types, such as ReqViewChange and ViewChange, that might cause generation of further new messages when generated and handled locally. These changes are required to avoid deadlocks and ensure that generated messages are handled locally in correct order. Please refer to individual commit message for more details.

### CODE REVIEW

**Comment by sergefdrv** [comment]
This draft PR borrows some commits from #148 to avoid data races in testing. Data races happen when Protobuf structure is marshalled and copied concurrently.

This PR needs to be rebased after #148 gets merged.

**Review by nhoriguchi — COMMENTED** [review]
Patch ["core: Rename abstractions dealing with peer messages"](https://github.com/hyperledger-labs/minbft/pull/152/commits/1b5f0e178a39f3105e120e564db052c3e8365a6d) define a new message category "peer message", so would it be more clear for the interface `Reply` in `messages/api.go` to embed something like `PeerMessage` instead of `ReplicaMessage`?

**Comment by sergefdrv** [comment]
> [...] would it be more clear for the interface `Reply` in `messages/api.go` to embed something like `PeerMessage` instead of `ReplicaMessage`?

I am not sure if we should invent a new term to classify message types sent by replicas to clients, which is only `Reply` message so far. But we might want to introduce `PeerMessage` interface:

```go
// PeerMessage represents a message exchanged between replicas.
type PeerMessage interface {
  ReplicaMessage
  ImplementsPeerMessage()
}
```

Then we would change the definitions of `Prepare` and `Commit` interfaces so that they must satisfy `PeerMessage` interface. So far, this only seems to be useful for making definitions of `peerMessageProcessor` and `peerMessageApplier` more specific, so that they only accept an instance of `messages.PeerMessage` as argument. However, this will additionally serve as an explicit definition of what is understood under "peer" message.

So I am going to add another commit to this PR and introduce `PeerMessage` interface. Thanks for you comment!

**Comment by sergefdrv** [comment]
Summary of [changes](https://github.com/hyperledger-labs/minbft/compare/1b5f0e178a39f3105e120e564db052c3e8365a6d..2e7b4865c68533960315ab47355b450e5c71e975):

 - Rebase with conflict resolution
 - Introduced `PeerMessage` interface (RFC)

**Comment by sergefdrv** [comment]
I marked the last commit https://github.com/hyperledger-labs/minbft/pull/152/commits/2e7b4865c68533960315ab47355b450e5c71e975 as RFC, because I was not sure if that makes things more clear or more complicated. I would like your opinion.

**Comment by nhoriguchi** [comment]
> I marked the last commit [2e7b486](https://github.com/hyperledger-labs/minbft/commit/2e7b4865c68533960315ab47355b450e5c71e975) as RFC, because I was not sure if that makes things more clear or more complicated. I would like your opinion.

The new interface looks fine to me, and it's great to add the clear definitions in code (that's finally included in godoc):
- `ReplicaMessage` represents a message generated by a replica.
- `PeerMessage` represents a message exchanged between replicas.

Thank you for you effort.

**Review by ynamiki — APPROVED** [review]
Looks good to me. Thanks.

**Comment by sergefdrv** [comment]
Summary of [changes](https://github.com/hyperledger-labs/minbft/compare/2e7b4865c68533960315ab47355b450e5c71e975..0f086514f74f89071c28ff0d0cbf5f5763bcadd6):

- Rebase
- Removed commits relating to peer messages (to be submitted in separate PR)

**Pull request merged**
