### PR TITLE
CircleCI: Update CI Environment to Ubuntu 18.04

### PR DESCRIPTION
**Pull request by ynamiki**
Intel SGX SDK 2.3 support Ubuntu 18.04. We can update the CI environment.

### CODE REVIEW

**Review by sergefdrv — APPROVED** [review]
Thanks!

**Review by nhoriguchi — APPROVED** [review]
Looks good to me, Thanks!

**Comment by sergefdrv** [comment]
@ynamiki There was some issue with GitHub yesterday. I think this is why DCO check got stuck. Maybe it will help if you change the PR, say update the commit message (like `s/support/supports/`), and force-push it?

**Comment by ynamiki** [comment]
@sergefdrv Now all checks have passed. Could you merge this?

**Pull request merged**
