### PR TITLE
peer request: multiple requests support v1

### LINKED ISSUE #100: Support submitting multiple requests in sample CLI
Beyond just simple demonstration, we might want to allow creating some workload. We can extend the sample `peer request` command to support submitting a series of requests back-to-back. Then this could be used to imitate some dense workload.

### PR DESCRIPTION
**Pull request by nhoriguchi**
This pull request is suggesting to update `peer request` subcommand to support issuing multiple requests in a single run.

Resolves #100

### CODE REVIEW

**Comment by sergefdrv** [comment]
I tried with two clients sending requests back-to-back concurrently, and it works:
```sh
for c in 0 1; do 
  for i in `seq 1 100`; do 
    echo Request $i; 
  done | bin/peer --id $c request & 
done
```

**Review by sergefdrv — APPROVED** [review]
Thanks! :+1:

**Comment by sergefdrv** [comment]
@Naoya-Horiguchi This time, CircleCI didn't work for you. I had to unfollow my personal fork of the project in CircleCI settings to make the PR check work. Maybe, there is a better way. 

What you can do with this PR is to amend the last commit, so that is has a new commit date, then force-push it. This used to trigger CircleCI again and made the GitHub check happy.

**Comment by nhoriguchi** [comment]
@sergefdrv Thanks for the info, I updated the branch and now Circle CI job has run.

**Comment by sergefdrv** [comment]
I noticed, when a PR branch is force-pushed, GitHub provides a link ("force-pushed") to check the changes:

image

I wonder if we'd better change our contribution guideline. Review comments could be addressed without opening another PR, but by force-pushing. The links would allow to check the changes, even more conveniently.

@Naoya-Horiguchi @ynamiki What do you think?

**Comment by nhoriguchi** [comment]
> I wonder if we'd better change our contribution guideline. Review comments could be addressed without opening another PR, but by force-pushing. The links would allow to check the changes, even more conveniently.
> 
> @Naoya-Horiguchi @ynamiki What do you think?

I'm fine about permitting force-push, especially if the new branch has just minor changes like typo fix.

**Review by ynamiki — APPROVED** [review]
Thanks!

**Comment by ynamiki** [comment]
> I wonder if we'd better change our contribution guideline. Review comments could be addressed without opening another PR, but by force-pushing. The links would allow to check the changes, even more conveniently.

👍 Thanks for finding the better way.

**Pull request merged**
