### PR TITLE
CircleCI: Use Pre-Built Docker Image v2

### PR DESCRIPTION
**Pull request by ynamiki**
This is v2 of #60.

Changes from v1:
- Make programs quiet: add `-qq` to `apt-get`, `-s` to `curl`

Note that, `apt-get` (actually, `dpkg` which is invoked inside) still have some outputs. To make completely quiet, apparently we can add `> /dev/null` or  an undocumented option`-o Dpkg::Use-Pty=0`. I don't use these (like "hacking") since I want not absolute silence but clean code and reasonable less outputs.

https://peteris.rocks/blog/quiet-and-unattended-installation-with-apt-get/

### CODE REVIEW

**Review by sergefdrv — APPROVED** [review]
Thanks!

**Review by nhoriguchi — APPROVED** [review]
Looks good to me, thank you.

**Comment by ynamiki** [comment]
I have deleted necblockchain/minbft repository in Docker Hub since we don't use the custom image anymore by merging this PR.

https://hub.docker.com/u/necblockchain

**Comment by sergefdrv** [comment]
@ynamiki The next step would be to update `go` and `gomatelinter`, together with reverting [the workaround for vendor directories](https://github.com/hyperledger-labs/minbft/commit/dfe3cf702ee335f11b6915896013cfac8f3d216a), right?

**Comment by ynamiki** [comment]
@sergefdrv Yes, I will do it tomorrow.

**Pull request merged**
