### PR TITLE
Decapitalize error strings

### LINKED ISSUE #105: Decapitalize error strings
Note: It is said that error strings should not be capitalized, but our project use the capitalized style consistently.
https://github.com/golang/go/wiki/CodeReviewComments#error-strings

_Originally posted by @ynamiki in https://github.com/hyperledger-labs/minbft/pull/102_

### LINKED ISSUE #106: Use `xerrors` package
What we could also do is to use ["github.com/pkg/errors" package](https://godoc.org/github.com/pkg/errors) for wrapping error messages in the context of the call stack.

_Originally posted by @sergefdrv in https://github.com/hyperledger-labs/minbft/pull/102/review_comment/create_

### PR DESCRIPTION
**Pull request by aki-tashiro**
resolves #105

----

This patch revises the first letter of the error log in "fmt.Errorf()" to lowercase.
In addition, words with uppercase meaning such as "Request" and "UI" are not revised.

Signed-off-by: Akiyoshi Tashiro <a_tashiro_29@nec.com>

----

This pull request is to lowercase the first letter of the error log in "fmt.Errorf ()".

@sergefdrv san, Thank you for [your comment](https://github.com/hyperledger-labs/minbft/issues/105#issuecomment-709902397).
I tried to fix "#106" together, but I thought there was something to discuss, so I revised it from #105 first.

### CODE REVIEW

**Review by ynamiki — COMMENTED** [review]
It is better to have a title in the commit message as follows:

```
Decapitalize error strings

This patch ...
```

I would like to know how you made this changes. Are the replacements done by a tool like `sed`?

**Comment by aki-tashiro** [comment]
@ynamiki san, 
Thank you for your comment.

> It is better to have a title in the commit message as follows:

Sorry, I rewrote the commit message.

> I would like to know how you made this changes. Are the replacements done by a tool like sed?

I searched all files in the MinBFT folder with "Errorf" and decapitalized error strings manually. (I used VS Code on Windows 10.)
However, words that should have an uppercase letter, such as "Request", "Prepare", and "UI", were not decapitalized.

**Review by ynamiki — COMMENTED** [review]
I found some more error strings that should be decapitalized:

```
% grep -r 'Errorf(\"[A-Z]' .
...
./sample/authentication/crypto.go:		return fmt.Errorf("Failed to calculate USIG key fingerprint: %s", err)
./sample/authentication/crypto.go:			return fmt.Errorf("Failed to parse UI certificate: %s", err)
./sample/authentication/crypto.go:		return fmt.Errorf("Failed to construct USIG identity: %s", err)
```

**Comment by nhoriguchi** [comment]
BTW, @Romeo5929 is now on transfer vacation. I hear that he will back on next Tuesday.

**Comment by aki-tashiro** [comment]
@ynamiki 
> I found some more error strings that should be decapitalized:

Thank you for pointing out mistakes.
I rewrote and updated "sample/authentication/crypto.go".

**Review by ynamiki — APPROVED** [review]
Thanks!

**Comment by sergefdrv** [comment]
The line "I tried to fix #106 together..." in the PR description will cause GitHub to mark #106 as resolved...

**Comment by aki-tashiro** [comment]
@sergefdrv 
I'm sorry I'm not used to using GitHub..
I rewrote it to "#106", but is there any problem?

**Review by nhoriguchi — APPROVED** [review]
Looks good to me.

**Pull request merged**
