### PR TITLE
Semi-automated view-change test

### LINKED ISSUE #243: Add semi-automated view-change test
Implement a script that periodically suspends and resumes replica processes. This will help to better test view-change functionality.

### PR DESCRIPTION
**Pull request by sergefdrv**
This pull request resolves #243.

### CODE REVIEW

**Comment by sergefdrv** [comment]
The test sometimes fails. One issue is that clients continue submitting requests when replicas are stopped, so some replicas get stopped before they have chance to deliver all the requests being processed. I have a fix for that. But the test also happen to fail from time to time because it takes too long to handle messages communicated during view change. Remember that checkpoints are not implemented yet to limit the size of the protocol history (#218). Implementation of ViewChange and NewView messages is also simple, but inefficient (#216).

**Comment by sergefdrv** [comment]
Summary of [changes](https://github.com/hyperledger-labs/minbft/compare/40fe97abf4137f720369a82a8d067a87cbb43288..1a2000ba3eac4e9649164f5bc6b1542d5da3aa71):
 - reduced default number of rounds
 - stopping clients before replicas

**Comment by sergefdrv** [comment]
The test is much more stable with lower number of rounds. It may still fail because view-change messages sometimes get too big and exceed gRPC limit. We may want to increase that limit in our sample application.

**Review by nhoriguchi — APPROVED** [review]
Looks good to me.  And I ran the script and confirmed to pass. This is also a good demonstration of view-change process.

**Pull request merged**
